#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWCF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTODO")]
	public partial class ContextoDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTAREA(TAREA instance);
    partial void UpdateTAREA(TAREA instance);
    partial void DeleteTAREA(TAREA instance);
    #endregion
		
		public ContextoDatosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDTODOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextoDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TAREA> TAREA
		{
			get
			{
				return this.GetTable<TAREA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAREA")]
	public partial class TAREA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TITULO;
		
		private string _NOTAS;
		
		private System.Nullable<int> _ESTADO;
		
		private System.Nullable<int> _PRIORIDAD;
		
		private System.Nullable<System.DateTime> _FECHA_CREACION;
		
		private System.Nullable<System.DateTime> _FECHA_TERMINO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTITULOChanging(string value);
    partial void OnTITULOChanged();
    partial void OnNOTASChanging(string value);
    partial void OnNOTASChanged();
    partial void OnESTADOChanging(System.Nullable<int> value);
    partial void OnESTADOChanged();
    partial void OnPRIORIDADChanging(System.Nullable<int> value);
    partial void OnPRIORIDADChanged();
    partial void OnFECHA_CREACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_CREACIONChanged();
    partial void OnFECHA_TERMINOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_TERMINOChanged();
    #endregion
		
		public TAREA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(400)")]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this.OnTITULOChanging(value);
					this.SendPropertyChanging();
					this._TITULO = value;
					this.SendPropertyChanged("TITULO");
					this.OnTITULOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTAS", DbType="VarChar(500)")]
		public string NOTAS
		{
			get
			{
				return this._NOTAS;
			}
			set
			{
				if ((this._NOTAS != value))
				{
					this.OnNOTASChanging(value);
					this.SendPropertyChanging();
					this._NOTAS = value;
					this.SendPropertyChanged("NOTAS");
					this.OnNOTASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
		public System.Nullable<int> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORIDAD", DbType="Int")]
		public System.Nullable<int> PRIORIDAD
		{
			get
			{
				return this._PRIORIDAD;
			}
			set
			{
				if ((this._PRIORIDAD != value))
				{
					this.OnPRIORIDADChanging(value);
					this.SendPropertyChanging();
					this._PRIORIDAD = value;
					this.SendPropertyChanged("PRIORIDAD");
					this.OnPRIORIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_CREACION
		{
			get
			{
				return this._FECHA_CREACION;
			}
			set
			{
				if ((this._FECHA_CREACION != value))
				{
					this.OnFECHA_CREACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREACION = value;
					this.SendPropertyChanged("FECHA_CREACION");
					this.OnFECHA_CREACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TERMINO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TERMINO
		{
			get
			{
				return this._FECHA_TERMINO;
			}
			set
			{
				if ((this._FECHA_TERMINO != value))
				{
					this.OnFECHA_TERMINOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TERMINO = value;
					this.SendPropertyChanged("FECHA_TERMINO");
					this.OnFECHA_TERMINOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
