//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetoWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TAREA", Namespace="http://schemas.datacontract.org/2004/07/ProyectoWCF")]
    [System.SerializableAttribute()]
    public partial class TAREA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_TERMINOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOTASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PRIORIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_CREACION {
            get {
                return this.FECHA_CREACIONField;
            }
            set {
                if ((this.FECHA_CREACIONField.Equals(value) != true)) {
                    this.FECHA_CREACIONField = value;
                    this.RaisePropertyChanged("FECHA_CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_TERMINO {
            get {
                return this.FECHA_TERMINOField;
            }
            set {
                if ((this.FECHA_TERMINOField.Equals(value) != true)) {
                    this.FECHA_TERMINOField = value;
                    this.RaisePropertyChanged("FECHA_TERMINO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOTAS {
            get {
                return this.NOTASField;
            }
            set {
                if ((object.ReferenceEquals(this.NOTASField, value) != true)) {
                    this.NOTASField = value;
                    this.RaisePropertyChanged("NOTAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PRIORIDAD {
            get {
                return this.PRIORIDADField;
            }
            set {
                if ((this.PRIORIDADField.Equals(value) != true)) {
                    this.PRIORIDADField = value;
                    this.RaisePropertyChanged("PRIORIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITULO {
            get {
                return this.TITULOField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULOField, value) != true)) {
                    this.TITULOField = value;
                    this.RaisePropertyChanged("TITULO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTareas", ReplyAction="http://tempuri.org/IService1/ObtenerTareasResponse")]
        RetoWeb.ServiceReference1.TAREA[] ObtenerTareas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTareas", ReplyAction="http://tempuri.org/IService1/ObtenerTareasResponse")]
        System.Threading.Tasks.Task<RetoWeb.ServiceReference1.TAREA[]> ObtenerTareasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarTarea", ReplyAction="http://tempuri.org/IService1/InsertarTareaResponse")]
        void InsertarTarea(RetoWeb.ServiceReference1.TAREA tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarTarea", ReplyAction="http://tempuri.org/IService1/InsertarTareaResponse")]
        System.Threading.Tasks.Task InsertarTareaAsync(RetoWeb.ServiceReference1.TAREA tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarTarea", ReplyAction="http://tempuri.org/IService1/EditarTareaResponse")]
        void EditarTarea(RetoWeb.ServiceReference1.TAREA tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarTarea", ReplyAction="http://tempuri.org/IService1/EditarTareaResponse")]
        System.Threading.Tasks.Task EditarTareaAsync(RetoWeb.ServiceReference1.TAREA tarea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarTarea", ReplyAction="http://tempuri.org/IService1/EliminarTareaResponse")]
        void EliminarTarea(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarTarea", ReplyAction="http://tempuri.org/IService1/EliminarTareaResponse")]
        System.Threading.Tasks.Task EliminarTareaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RetoWeb.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RetoWeb.ServiceReference1.IService1>, RetoWeb.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RetoWeb.ServiceReference1.TAREA[] ObtenerTareas() {
            return base.Channel.ObtenerTareas();
        }
        
        public System.Threading.Tasks.Task<RetoWeb.ServiceReference1.TAREA[]> ObtenerTareasAsync() {
            return base.Channel.ObtenerTareasAsync();
        }
        
        public void InsertarTarea(RetoWeb.ServiceReference1.TAREA tarea) {
            base.Channel.InsertarTarea(tarea);
        }
        
        public System.Threading.Tasks.Task InsertarTareaAsync(RetoWeb.ServiceReference1.TAREA tarea) {
            return base.Channel.InsertarTareaAsync(tarea);
        }
        
        public void EditarTarea(RetoWeb.ServiceReference1.TAREA tarea) {
            base.Channel.EditarTarea(tarea);
        }
        
        public System.Threading.Tasks.Task EditarTareaAsync(RetoWeb.ServiceReference1.TAREA tarea) {
            return base.Channel.EditarTareaAsync(tarea);
        }
        
        public void EliminarTarea(int id) {
            base.Channel.EliminarTarea(id);
        }
        
        public System.Threading.Tasks.Task EliminarTareaAsync(int id) {
            return base.Channel.EliminarTareaAsync(id);
        }
    }
}
